name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Deploy to Cloud Run
      env:
        GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
        GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
      run: |
        echo $GCLOUD_SERVICE_KEY | base64 -d > key.json
        gcloud auth activate-service-account --key-file=key.json
        gcloud config set project $GCLOUD_PROJECT
        gcloud run deploy telegram-bot \
          --source . \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
